// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"database/sql"
	"time"
)

type File struct {
	ID           string    `json:"id"`
	OriginalName string    `json:"original_name"`
	Size         int64     `json:"size"`
	ContentType  string    `json:"content_type"`
	StorageKey   string    `json:"storage_key"`
	Downloads    int32     `json:"downloads"`
	MaxDownloads int32     `json:"max_downloads"`
	CreatedAt    time.Time `json:"created_at"`
	ExpiresAt    time.Time `json:"expires_at"`
}

type Paste struct {
	ID        string         `json:"id"`
	Content   string         `json:"content"`
	Language  string         `json:"language"`
	Title     sql.NullString `json:"title"`
	Views     int32          `json:"views"`
	MaxViews  int32          `json:"max_views"`
	CreatedAt time.Time      `json:"created_at"`
	ExpiresAt time.Time      `json:"expires_at"`
}
