// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package postgres

import (
	"context"
)

type Querier interface {
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreatePaste(ctx context.Context, arg CreatePasteParams) (Paste, error)
	DeleteExpiredFiles(ctx context.Context) error
	DeleteExpiredPastes(ctx context.Context) error
	GetFileByID(ctx context.Context, id string) (File, error)
	GetPasteByID(ctx context.Context, id string) (Paste, error)
	IncrementFileDownloads(ctx context.Context, id string) error
	IncrementPasteViews(ctx context.Context, id string) error
}

var _ Querier = (*Queries)(nil)
